[config.rag.setup]
index_name = "diploma"
text_node_property = "text"
similarity_top_k = 10
vector_store_query_mode = "default"
# similarity_cutoff = 0.75
response_mode = "compact"
distance_strategy = "cosine"
embedding_dimension = 128
chunk_size = 512
chunk_overlap = 0.2
separator = " "
max_function_calls = 2
hybrid_search = false

[config.rag.models]
llm_openai = "gpt-4o-mini"
llm_google = "gemini-2.0-flash-lite"
em_openai = "text-embedding-3-small"
temperature = 0

[config.env]
OPENAI_API_KEY = "YOUR_API_KEY_HERE"
GEMINI_API_KEY = "YOUR_API_KEY_HERE"
NEO4J_URI = "YOUR_NEO4J_URI_HERE"
NEO4J_USER = "YOUR_USERNAME_HERE"
NEO4J_PASSWORD = "YOUR_PASSWORD_HERE"
